# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnunitydemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rnunitydemo

end
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end